### ISSUE TITLE
upgrade to babel-plugin-macros

### ISSUE THREAD

**Issue by kentcdodds** [mattphillips/babel-plugin-console#4]
I think you're running on a rather old version of `babel-macros` so there will be a handful of changes you'll need to make (in addition to some docs updates and make sure you add `babel-plugin-macros` to the `keywords` in your `package.json`).

I suggest reading through [the author docs](https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md) briefly to make sure you don't miss anything.

`babel-plugin-macros` is about to become big with the release of CRA v2.0 and I'd love your plugin to be a part of that!

**Comment by mattphillips** [comment]
Hey @kentcdodds thanks for the heads up! I've just published this with the updated version of babel-plugin-macros, congrats on getting support in CRA 🎉

**Comment by kentcdodds** [comment]
Awesome! Thanks!
